# WORKDAY_COMPANIES = [
#     # --- TECH CORNERSTONES & HOT TECH CENTERS ---
#     {"name": "salesforce", "provider": "workday", "base_url": "https://salesforce.wd1.myworkdayjobs.com/ExternalCareerSite"},
#     {"name": "qualcomm", "provider": "workday", "base_url": "https://qualcomm.wd5.myworkdayjobs.com/External"},
#     {"name": "nvidia", "provider": "workday", "base_url": "https://nvidia.wd5.myworkdayjobs.com/NVIDIAExternalCareerSite"},
#     {"name": "amd", "provider": "workday", "base_url": "https://amd.wd1.myworkdayjobs.com/AMD_External_Careers"},
#     {"name": "intel", "provider": "workday", "base_url": "https://intel.wd1.myworkdayjobs.com/External"},
#     {"name": "cisco", "provider": "workday", "base_url": "https://cisco.wd5.myworkdayjobs.com/Official_Cisco_Careers"},
#     {"name": "dell", "provider": "workday", "base_url": "https://dell.wd1.myworkdayjobs.com/External"},
#     {"name": "hp", "provider": "workday", "base_url": "https://hp.wd5.myworkdayjobs.com/ExternalCareers"},
#     {"name": "hpe", "provider": "workday", "base_url": "https://hpe.wd5.myworkdayjobs.com/Jobsathpe"},
#     {"name": "adobe", "provider": "workday", "base_url": "https://adobe.wd5.myworkdayjobs.com/externalcareers"},
#     {"name": "autodesk", "provider": "workday", "base_url": "https://autodesk.wd1.myworkdayjobs.com/Ext"},
#     {"name": "vmware", "provider": "workday", "base_url": "https://vmware.wd1.myworkdayjobs.com/VMware"},
#     {"name": "netapp", "provider": "workday", "base_url": "https://netapp.wd1.myworkdayjobs.com/ExternalCareers"},
#     {"name": "nutanix", "provider": "workday", "base_url": "https://nutanix.wd1.myworkdayjobs.com/NutanixCareers"},
#     {"name": "purestorage", "provider": "workday", "base_url": "https://purestorage.wd1.myworkdayjobs.com/External"},
#     {"name": "citrix", "provider": "workday", "base_url": "https://citrix.wd1.myworkdayjobs.com/CitrixCareers"},
#     {"name": "akamai", "provider": "workday", "base_url": "https://akamai.wd1.myworkdayjobs.com/AkamaiCareers"},
#     {"name": "f5", "provider": "workday", "base_url": "https://f5.wd1.myworkdayjobs.com/f5careers"},
#     {"name": "paloaltonetworks", "provider": "workday", "base_url": "https://paloaltonetworks.wd1.myworkdayjobs.com/External"},
#     {"name": "fortinet", "provider": "workday", "base_url": "https://fortinet.wd1.myworkdayjobs.com/FortinetCareers"},
#     {"name": "crowdstrike", "provider": "workday", "base_url": "https://crowdstrike.wd5.myworkdayjobs.com/crowdstrike"},
#     {"name": "cloudflare", "provider": "workday", "base_url": "https://cloudflare.wd1.myworkdayjobs.com/Cloudflare"},
#     {"name": "okta", "provider": "workday", "base_url": "https://okta.wd1.myworkdayjobs.com/External"},
#     {"name": "servicenow", "provider": "workday", "base_url": "https://servicenow.wd1.myworkdayjobs.com/ServiceNowCareers"},
#     {"name": "workday", "provider": "workday", "base_url": "https://workday.wd5.myworkdayjobs.com/Workday"},
#     {"name": "splunk", "provider": "workday", "base_url": "https://splunk.wd1.myworkdayjobs.com/SplunkCareers"},
#     {"name": "datadog", "provider": "workday", "base_url": "https://datadog.wd1.myworkdayjobs.com/External"},
#     {"name": "dynatrace", "provider": "workday", "base_url": "https://dynatrace.wd1.myworkdayjobs.com/External"},
#     {"name": "newrelic", "provider": "workday", "base_url": "https://newrelic.wd1.myworkdayjobs.com/External"},
#     {"name": "elastic", "provider": "workday", "base_url": "https://elastic.wd1.myworkdayjobs.com/Elastic"},

#     # --- INDIAN TECH & TRAVEL POWERHOUSES ---
#     {"name": "makemytrip", "provider": "workday", "base_url": "https://makemytrip.wd3.myworkdayjobs.com/MMT"},
#     {"name": "myntra", "provider": "workday", "base_url": "https://myntra.wd1.myworkdayjobs.com/Myntra_Careers"},
#     {"name": "flipkart", "provider": "workday", "base_url": "https://flipkart.wd1.myworkdayjobs.com/Flipkart_Careers"},
#     {"name": "ajio", "provider": "workday", "base_url": "https://reliance.wd3.myworkdayjobs.com/RelianceCareers"},
#     {"name": "paytm", "provider": "workday", "base_url": "https://paytm.wd1.myworkdayjobs.com/Paytm_Careers"},
#     {"name": "ola", "provider": "workday", "base_url": "https://ola.wd1.myworkdayjobs.com/Ola_Careers"},
#     {"name": "jio", "provider": "workday", "base_url": "https://jio.wd3.myworkdayjobs.com/Jio_Careers"},
#     {"name": "tcs", "provider": "workday", "base_url": "https://tcs.wd3.myworkdayjobs.com/TCS_Global_Careers"},
#     {"name": "infosys", "provider": "workday", "base_url": "https://infosys.wd3.myworkdayjobs.com/Infosys_Careers"},
#     {"name": "wipro", "provider": "workday", "base_url": "https://wipro.wd3.myworkdayjobs.com/Wipro_External_Careers"},
#     {"name": "hcltech", "provider": "workday", "base_url": "https://hcl.wd3.myworkdayjobs.com/HCLTech_Careers"},
#     {"name": "techmahindra", "provider": "workday", "base_url": "https://techmahindra.wd3.myworkdayjobs.com/TechM_Careers"},
#     {"name": "mindtree", "provider": "workday", "base_url": "https://ltimindtree.wd3.myworkdayjobs.com/External"},
#     {"name": "cognizant", "provider": "workday", "base_url": "https://cognizant.wd3.myworkdayjobs.com/Cognizant_Careers"},
#     {"name": "persistent", "provider": "workday", "base_url": "https://persistent.wd3.myworkdayjobs.com/Persistent_External_Careers"},
#     {"name": "mphasis", "provider": "workday", "base_url": "https://mphasis.wd3.myworkdayjobs.com/Careers"},
#     {"name": "coforge", "provider": "workday", "base_url": "https://coforge.wd3.myworkdayjobs.com/Coforge_Careers"},
#     {"name": "cyrient", "provider": "workday", "base_url": "https://cyrient.wd3.myworkdayjobs.com/External"},
#     {"name": "zensar", "provider": "workday", "base_url": "https://zensar.wd3.myworkdayjobs.com/Zensar_Careers"},
#     {"name": "virtusa", "provider": "workday", "base_url": "https://virtusa.wd3.myworkdayjobs.com/Virtusa_Careers"},

#     # --- GLOBAL CAPTIVES & R&D IN INDIA (GCCs) ---
#     {"name": "walmart", "provider": "workday", "base_url": "https://walmart.wd5.myworkdayjobs.com/WalmartIndiaCareers"},
#     {"name": "target", "provider": "workday", "base_url": "https://target.wd5.myworkdayjobs.com/targetcareers"},
#     {"name": "amazon", "provider": "workday", "base_url": "https://amazon.wd5.myworkdayjobs.com/AWS_External_Career_Site"},
#     {"name": "siemens", "provider": "workday", "base_url": "https://siemens.wd5.myworkdayjobs.com/Siemens_Careers"},
#     {"name": "ge", "provider": "workday", "base_url": "https://ge.wd5.myworkdayjobs.com"},
#     {"name": "philips", "provider": "workday", "base_url": "https://philips.wd3.myworkdayjobs.com/Employment-Engineering"},
#     {"name": "schneider", "provider": "workday", "base_url": "https://schneider-electric.wd3.myworkdayjobs.com/SchneiderCareers"},
#     {"name": "abb", "provider": "workday", "base_url": "https://abb.wd3.myworkdayjobs.com/ABBCareers"},
#     {"name": "honeywell", "provider": "workday", "base_url": "https://honeywell.wd5.myworkdayjobs.com/HoneywellCareers"},
#     {"name": "bosch", "provider": "workday", "base_url": "https://bosch.wd3.myworkdayjobs.com/BoschCareers"},
#     {"name": "eaton", "provider": "workday", "base_url": "https://eaton.wd5.myworkdayjobs.com/EatonCareers"},
#     {"name": "rockwell", "provider": "workday", "base_url": "https://rockwellautomation.wd1.myworkdayjobs.com/ExternalCareers"},
#     {"name": "emerson", "provider": "workday", "base_url": "https://emerson.wd5.myworkdayjobs.com/EmersonCareers"},
#     {"name": "caterpillar", "provider": "workday", "base_url": "https://caterpillar.wd5.myworkdayjobs.com/CaterpillarCareers"},
#     {"name": "johndeere", "provider": "workday", "base_url": "https://johndeere.wd5.myworkdayjobs.com/JohnDeereCareers"},
#     {"name": "cummins", "provider": "workday", "base_url": "https://cummins.wd5.myworkdayjobs.com/CumminsCareers"},
#     {"name": "rollsroyce", "provider": "workday", "base_url": "https://rollsroyce.wd3.myworkdayjobs.com/RollsRoyceCareers"},
#     {"name": "boeing", "provider": "workday", "base_url": "https://boeing.wd1.myworkdayjobs.com/BoeingCareers"},
#     {"name": "airbus", "provider": "workday", "base_url": "https://airbus.wd3.myworkdayjobs.com/AirbusCareers"},
#     {"name": "lockheedmartin", "provider": "workday", "base_url": "https://lockheedmartin.wd1.myworkdayjobs.com/External"},

#     # --- BANKING, FINTECH & QUANT INSIGHTS ---
#     {"name": "paypal", "provider": "workday", "base_url": "https://paypal.wd1.myworkdayjobs.com"},
#     {"name": "stripe", "provider": "workday", "base_url": "https://stripe.wd1.myworkdayjobs.com/StripeCareers"},
#     {"name": "mastercard", "provider": "workday", "base_url": "https://mastercard.wd1.myworkdayjobs.com/CorporateCareers"},
#     {"name": "visa", "provider": "workday", "base_url": "https://visa.wd1.myworkdayjobs.com/VisaCareers"},
#     {"name": "americanexpress", "provider": "workday", "base_url": "https://amex.wd5.myworkdayjobs.com/AmexCareers"},
#     {"name": "capitalone", "provider": "workday", "base_url": "https://capitalone.wd1.myworkdayjobs.com/CapitalOne"},
#     {"name": "goldmansachs", "provider": "workday", "base_url": "https://goldmansachs.wd5.myworkdayjobs.com/GoldmanSachsCareers"},
#     {"name": "morganstanley", "provider": "workday", "base_url": "https://morganstanley.wd5.myworkdayjobs.com/GCO"},
#     {"name": "jpmorgan", "provider": "workday", "base_url": "https://jpmorgan.wd5.myworkdayjobs.com/JPM_Careers"},
#     {"name": "citigroup", "provider": "workday", "base_url": "https://citi.wd5.myworkdayjobs.com/CitiCareers"},
#     {"name": "bankofamerica", "provider": "workday", "base_url": "https://bofa.wd1.myworkdayjobs.com/External"},
#     {"name": "wellsfargo", "provider": "workday", "base_url": "https://wellsfargo.wd5.myworkdayjobs.com/WellsFargoCareers"},
#     {"name": "hsbc", "provider": "workday", "base_url": "https://hsbc.wd5.myworkdayjobs.com/HSBC_Careers"},
#     {"name": "standardchartered", "provider": "workday", "base_url": "https://sc.wd5.myworkdayjobs.com/SC_Careers"},
#     {"name": "barclays", "provider": "workday", "base_url": "https://barclays.wd3.myworkdayjobs.com/BarclaysCareers"},
#     {"name": "db", "provider": "workday", "base_url": "https://db.wd3.myworkdayjobs.com/DeutscheBankCareers"},
#     {"name": "ubs", "provider": "workday", "base_url": "https://ubs.wd5.myworkdayjobs.com/UBS_Careers"},
#     {"name": "credit-suisse", "provider": "workday", "base_url": "https://creditsuisse.wd5.myworkdayjobs.com/CS_Careers"},
#     {"name": "bny-mellon", "provider": "workday", "base_url": "https://bnymellon.wd5.myworkdayjobs.com/BNYMellonCareers"},
#     {"name": "northern-trust", "provider": "workday", "base_url": "https://northerntrust.wd1.myworkdayjobs.com/External"},
#     {"name": "state-street", "provider": "workday", "base_url": "https://statestreet.wd1.myworkdayjobs.com/StateStreetCareers"},
#     {"name": "fidelity", "provider": "workday", "base_url": "https://fil.wd3.myworkdayjobs.com/001"},
#     {"name": "blackrock", "provider": "workday", "base_url": "https://blackrock.wd1.myworkdayjobs.com/BlackRock_Professional"},
#     {"name": "vanguard", "provider": "workday", "base_url": "https://vanguard.wd1.myworkdayjobs.com/Vanguard_Careers"},
#     {"name": "franklin-templeton", "provider": "workday", "base_url": "https://franklintempleton.wd1.myworkdayjobs.com/External"},
#     {"name": "invesco", "provider": "workday", "base_url": "https://invesco.wd1.myworkdayjobs.com/InvescoCareers"},
#     {"name": "schroders", "provider": "workday", "base_url": "https://schroders.wd3.myworkdayjobs.com/SchrodersCareers"},
#     {"name": "alliancebernstein", "provider": "workday", "base_url": "https://alliancebernstein.wd1.myworkdayjobs.com/ABCareers"},
#     {"name": "blackstone", "provider": "workday", "base_url": "https://blackstone.wd1.myworkdayjobs.com/Blackstone_Careers"},
#     {"name": "kkr", "provider": "workday", "base_url": "https://kkr.wd1.myworkdayjobs.com/KKR_Careers"},

#     # --- TOP TELECOM, NETWORK & SEMICONDUCTOR ---
#     {"name": "broadcom", "provider": "workday", "base_url": "https://broadcom.wd1.myworkdayjobs.com/External_Career"},
#     {"name": "mediatek", "provider": "workday", "base_url": "https://mediatek.wd3.myworkdayjobs.com/MediaTekCareers"},
#     {"name": "marvell", "provider": "workday", "base_url": "https://marvell.wd1.myworkdayjobs.com/MarvellCareers"},
#     {"name": "nxp", "provider": "workday", "base_url": "https://nxp.wd3.myworkdayjobs.com/NXPCareers"},
#     {"name": "infineon", "provider": "workday", "base_url": "https://infineon.wd3.myworkdayjobs.com/InfineonCareers"},
#     {"name": "stmicroelectronics", "provider": "workday", "base_url": "https://st.wd3.myworkdayjobs.com/STMicroelectronics_Careers"},
#     {"name": "analogdevices", "provider": "workday", "base_url": "https://analogdevices.wd1.myworkdayjobs.com/ADICareers"},
#     {"name": "texasinstruments", "provider": "workday", "base_url": "https://ti.wd1.myworkdayjobs.com/TICareers"},
#     {"name": "appliedmaterials", "provider": "workday", "base_url": "https://amat.wd1.myworkdayjobs.com/AppliedMaterialsCareers"},
#     {"name": "lamresearch", "provider": "workday", "base_url": "https://lamresearch.wd1.myworkdayjobs.com/LamCareers"},
#     {"name": "asml", "provider": "workday", "base_url": "https://asml.wd3.myworkdayjobs.com/ASML_Careers"},
#     {"name": "tokyo-electron", "provider": "workday", "base_url": "https://tel.wd3.myworkdayjobs.com/TELCareers"},
#     {"name": "synopsys", "provider": "workday", "base_url": "https://synopsys.wd1.myworkdayjobs.com/SynopsysCareers"},
#     {"name": "cadence", "provider": "workday", "base_url": "https://cadence.wd1.myworkdayjobs.com/CadenceCareers"},
#     {"name": "ansys", "provider": "workday", "base_url": "https://ansys.wd1.myworkdayjobs.com/AnsysCareers"},
#     {"name": "juniper", "provider": "workday", "base_url": "https://juniper.wd1.myworkdayjobs.com/JuniperCareers"},
#     {"name": "ciena", "provider": "workday", "base_url": "https://ciena.wd1.myworkdayjobs.com/CienaCareers"},
#     {"name": "nokia", "provider": "workday", "base_url": "https://nokia.wd3.myworkdayjobs.com/NokiaCareers"},
#     {"name": "ericsson", "provider": "workday", "base_url": "https://ericsson.wd3.myworkdayjobs.com/EricssonCareers"},
#     {"name": "vodafone", "provider": "workday", "base_url": "https://vodafone.wd3.myworkdayjobs.com/VodafoneCareers"},

#     # --- MAJOR INFRASTRUCTURE & BIG CLOUD LAYERS ---
#     {"name": "kyndryl", "provider": "workday", "base_url": "https://kyndryl.wd5.myworkdayjobs.com/KyndrylProfessionalCareers"},
#     {"name": "equinix", "provider": "workday", "base_url": "https://equinix.wd1.myworkdayjobs.com/EquinixCareers"},
#     {"name": "digitalrealty", "provider": "workday", "base_url": "https://digitalrealty.wd1.myworkdayjobs.com/DigitalRealtyCareers"},
#     {"name": "rackspace", "provider": "workday", "base_url": "https://rackspace.wd1.myworkdayjobs.com/RackspaceCareers"},
#     {"name": "ironmountain", "provider": "workday", "base_url": "https://ironmountain.wd1.myworkdayjobs.com/IronMountainCareers"},
#     {"name": "opentext", "provider": "workday", "base_url": "https://opentext.wd1.myworkdayjobs.com/OpenTextCareers"},
#     {"name": "box", "provider": "workday", "base_url": "https://box.wd1.myworkdayjobs.com/BoxCareers"},
#     {"name": "dropbox", "provider": "workday", "base_url": "https://dropbox.wd1.myworkdayjobs.com/DropboxCareers"},
#     {"name": "salesforce-mulesoft", "provider": "workday", "base_url": "https://salesforce.wd1.myworkdayjobs.com/MuleSoft_Careers"},
#     {"name": "salesforce-tableau", "provider": "workday", "base_url": "https://salesforce.wd1.myworkdayjobs.com/Tableau_Careers"},
#     {"name": "sap", "provider": "workday", "base_url": "https://sap.wd3.myworkdayjobs.com/SAP_Careers"},
#     {"name": "oracle", "provider": "workday", "base_url": "https://oracle.wd1.myworkdayjobs.com/OracleCareers"},
#     {"name": "ibm", "provider": "workday", "base_url": "https://ibm.wd1.myworkdayjobs.com/IBMCareers"},
#     {"name": "microsoft", "provider": "workday", "base_url": "https://microsoft.wd1.myworkdayjobs.com/MicrosoftCareers"},
#     {"name": "redhat", "provider": "workday", "base_url": "https://redhat.wd1.myworkdayjobs.com/RedHatCareers"},
#     {"name": "suse", "provider": "workday", "base_url": "https://suse.wd3.myworkdayjobs.com/SUSECareers"},
#     {"name": "canonical", "provider": "workday", "base_url": "https://canonical.wd1.myworkdayjobs.com/CanonicalCareers"},
#     {"name": "confluent", "provider": "workday", "base_url": "https://confluent.wd1.myworkdayjobs.com/ConfluentCareers"},
#     {"name": "snowflake", "provider": "workday", "base_url": "https://snowflake.wd1.myworkdayjobs.com/SnowflakeCareers"},
#     {"name": "mongodb", "provider": "workday", "base_url": "https://mongodb.wd1.myworkdayjobs.com/MongoDBCareers"},

#     # --- TOP AUTOMOTIVE TECH & EV RESEARCH ---
#     {"name": "tesla", "provider": "workday", "base_url": "https://tesla.wd1.myworkdayjobs.com/TeslaCareers"},
#     {"name": "rivian", "provider": "workday", "base_url": "https://rivian.wd1.myworkdayjobs.com/RivianCareers"},
#     {"name": "lucid", "provider": "workday", "base_url": "https://lucidmotors.wd1.myworkdayjobs.com/LucidCareers"},
#     {"name": "ford", "provider": "workday", "base_url": "https://ford.wd5.myworkdayjobs.com/FordCareers"},
#     {"name": "gm", "provider": "workday", "base_url": "https://gm.wd5.myworkdayjobs.com/GMCareers"},
#     {"name": "stellantis", "provider": "workday", "base_url": "https://stellantis.wd3.myworkdayjobs.com/StellantisCareers"},
#     {"name": "toyota", "provider": "workday", "base_url": "https://toyota.wd5.myworkdayjobs.com/ToyotaCareers"},
#     {"name": "honda", "provider": "workday", "base_url": "https://honda.wd5.myworkdayjobs.com/HondaCareers"},
#     {"name": "nissan", "provider": "workday", "base_url": "https://nissan.wd3.myworkdayjobs.com/NissanCareers"},
#     {"name": "hyundai", "provider": "workday", "base_url": "https://hyundai.wd5.myworkdayjobs.com/HyundaiCareers"},
#     {"name": "kia", "provider": "workday", "base_url": "https://kia.wd5.myworkdayjobs.com/KiaCareers"},
#     {"name": "bmw", "provider": "workday", "base_url": "https://bmw.wd3.myworkdayjobs.com/BMWCareers"},
#     {"name": "mercedes-benz", "provider": "workday", "base_url": "https://mercedesbenz.wd3.myworkdayjobs.com/MercedesBenzCareers"},
#     {"name": "audi", "provider": "workday", "base_url": "https://audi.wd3.myworkdayjobs.com/AudiCareers"},
#     {"name": "volkswagen", "provider": "workday", "base_url": "https://vw.wd3.myworkdayjobs.com/VWCareers"},
#     {"name": "volvo", "provider": "workday", "base_url": "https://volvo.wd3.myworkdayjobs.com/VolvoCareers"},
#     {"name": "tatamotors", "provider": "workday", "base_url": "https://tata.wd3.myworkdayjobs.com/TataMotorsCareers"},
#     {"name": "mahindra", "provider": "workday", "base_url": "https://mahindra.wd3.myworkdayjobs.com/MahindraCareers"},
#     {"name": "marutisuzuki", "provider": "workday", "base_url": "https://maruti.wd3.myworkdayjobs.com/MarutiCareers"},
#     {"name": "bajaj", "provider": "workday", "base_url": "https://bajaj.wd3.myworkdayjobs.com/BajajCareers"},

#     # --- TOP PHARMA, GLOBAL R&D LABS & HEALTH TECH ---
#     {"name": "pfizer", "provider": "workday", "base_url": "https://pfizer.wd1.myworkdayjobs.com/PfizerCareers"},
#     {"name": "novartis", "provider": "workday", "base_url": "https://novartis.wd3.myworkdayjobs.com/NovartisCareers"},
#     {"name": "roche", "provider": "workday", "base_url": "https://roche.wd3.myworkdayjobs.com/RocheCareers"},
#     {"name": "merck", "provider": "workday", "base_url": "https://merck.wd1.myworkdayjobs.com/MerckCareers"},
#     {"name": "bristol-myers", "provider": "workday", "base_url": "https://bms.wd1.myworkdayjobs.com/BMSCareers"},
#     {"name": "astrazeneca", "provider": "workday", "base_url": "https://astrazeneca.wd3.myworkdayjobs.com/AZCareers"},
#     {"name": "gsk", "provider": "workday", "base_url": "https://gsk.wd3.myworkdayjobs.com/GSKCareers"},
#     {"name": "sanofi", "provider": "workday", "base_url": "https://sanofi.wd3.myworkdayjobs.com/SanofiCareers"},
#     {"name": "abbvie", "provider": "workday", "base_url": "https://abbvie.wd1.myworkdayjobs.com/AbbVieCareers"},
#     {"name": "eli-lilly", "provider": "workday", "base_url": "https://lilly.wd1.myworkdayjobs.com/LillyCareers"},
#     {"name": "amgen", "provider": "workday", "base_url": "https://amgen.wd1.myworkdayjobs.com/AmgenCareers"},
#     {"name": "gilead", "provider": "workday", "base_url": "https://gilead.wd1.myworkdayjobs.com/GileadCareers"},
#     {"name": "biogen", "provider": "workday", "base_url": "https://biogen.wd1.myworkdayjobs.com/BiogenCareers"},
#     {"name": "moderna", "provider": "workday", "base_url": "https://moderna.wd1.myworkdayjobs.com/ModernaCareers"},
#     {"name": "bayer", "provider": "workday", "base_url": "https://bayer.wd3.myworkdayjobs.com/BayerCareers"},
#     {"name": "thermofisher", "provider": "workday", "base_url": "https://thermofisher.wd1.myworkdayjobs.com/ThermoFisherCareers"},
#     {"name": "danaher", "provider": "workday", "base_url": "https://danaher.wd1.myworkdayjobs.com/DanaherCareers"},
#     {"name": "medtronic", "provider": "workday", "base_url": "https://medtronic.wd1.myworkdayjobs.com/MedtronicCareers"},
#     {"name": "stryker", "provider": "workday", "base_url": "https://stryker.wd1.myworkdayjobs.com/StrykerCareers"},
#     {"name": "baxter", "provider": "workday", "base_url": "https://baxter.wd1.myworkdayjobs.com/BaxterCareers"},

#     # --- TOP GLOBAL CONSULTING & PROFESSIONAL SERVICES ---
#     {"name": "accenture", "provider": "workday", "base_url": "https://accenture.wd3.myworkdayjobs.com/AccentureCareers"},
#     {"name": "deloitte", "provider": "workday", "base_url": "https://deloitte.wd1.myworkdayjobs.com/DeloitteCareers"},
#     {"name": "ey", "provider": "workday", "base_url": "https://ey.wd3.myworkdayjobs.com/EYCareers"},
#     {"name": "pwc", "provider": "workday", "base_url": "https://pwc.wd3.myworkdayjobs.com/PWCCareers"},
#     {"name": "kpmg", "provider": "workday", "base_url": "https://kpmg.wd3.myworkdayjobs.com/KPMGCareers"},
#     {"name": "mckinsey", "provider": "workday", "base_url": "https://mckinsey.wd1.myworkdayjobs.com/McKinseyCareers"},
#     {"name": "bcg", "provider": "workday", "base_url": "https://bcg.wd1.myworkdayjobs.com/BCGCareers"},
#     {"name": "bain", "provider": "workday", "base_url": "https://bain.wd1.myworkdayjobs.com/BainCareers"},
#     {"name": "oliverwyman", "provider": "workday", "base_url": "https://mmc.wd1.myworkdayjobs.com/OliverWyman"},
#     {"name": "gartner", "provider": "workday", "base_url": "https://gartner.wd1.myworkdayjobs.com/GartnerCareers"},
#     {"name": "forrester", "provider": "workday", "base_url": "https://forrester.wd1.myworkdayjobs.com/ForresterCareers"},
#     {"name": "idc", "provider": "workday", "base_url": "https://idc.wd1.myworkdayjobs.com/IDCCareers"},
#     {"name": "genpact", "provider": "workday", "base_url": "https://genpact.wd3.myworkdayjobs.com/GenpactCareers"},
#     {"name": "exl", "provider": "workday", "base_url": "https://exl.wd3.myworkdayjobs.com/EXLCareers"},
#     {"name": "wns", "provider": "workday", "base_url": "https://wns.wd3.myworkdayjobs.com/WNSCareers"},
#     {"name": "concentrix", "provider": "workday", "base_url": "https://concentrix.wd3.myworkdayjobs.com/ConcentrixCareers"},
#     {"name": "teleperformance", "provider": "workday", "base_url": "https://teleperformance.wd3.myworkdayjobs.com/TPCareers"},
#     {"name": "trizetto", "provider": "workday", "base_url": "https://cognizant.wd3.myworkdayjobs.com/TriZettoCareers"},
#     {"name": "capgemini", "provider": "workday", "base_url": "https://capgemini.wd3.myworkdayjobs.com/CapgeminiCareers"},
#     {"name": "atos", "provider": "workday", "base_url": "https://atos.wd3.myworkdayjobs.com/AtosCareers"},

#     # --- TOP RETAIL & FMCG TECHNOLOGY HUBS ---
#     {"name": "unilever", "provider": "workday", "base_url": "https://unilever.wd3.myworkdayjobs.com/UnileverCareers"},
#     {"name": "pg", "provider": "workday", "base_url": "https://pg.wd1.myworkdayjobs.com/PGCareers"},
#     {"name": "nestle", "provider": "workday", "base_url": "https://nestle.wd3.myworkdayjobs.com/NestleCareers"},
#     {"name": "pepsico", "provider": "workday", "base_url": "https://pepsico.wd1.myworkdayjobs.com/PepsiCoCareers"},
#     {"name": "cocacola", "provider": "workday", "base_url": "https://coca-cola.wd1.myworkdayjobs.com/CocaColaCareers"},
#     {"name": "danone", "provider": "workday", "base_url": "https://danone.wd3.myworkdayjobs.com/DanoneCareers"},
#     {"name": "mars", "provider": "workday", "base_url": "https://mars.wd1.myworkdayjobs.com/MarsCareers"},
#     {"name": "mondelez", "provider": "workday", "base_url": "https://mondelez.wd1.myworkdayjobs.com/MondelezCareers"},
#     {"name": "kraftheinz", "provider": "workday", "base_url": "https://kraftheinz.wd1.myworkdayjobs.com/KraftHeinzCareers"},
#     {"name": "generalmills", "provider": "workday", "base_url": "https://generalmills.wd1.myworkdayjobs.com/GeneralMillsCareers"},
#     {"name": "kellogg", "provider": "workday", "base_url": "https://kellogg.wd1.myworkdayjobs.com/KelloggCareers"},
#     {"name": "reckitt", "provider": "workday", "base_url": "https://reckitt.wd3.myworkdayjobs.com/ReckittCareers"},
#     {"name": "loreal", "provider": "workday", "base_url": "https://loreal.wd3.myworkdayjobs.com/LorealCareers"},
#     {"name": "estee-lauder", "provider": "workday", "base_url": "https://elc.wd1.myworkdayjobs.com/EsteeLauderCareers"},
#     {"name": "diageo", "provider": "workday", "base_url": "https://diageo.wd3.myworkdayjobs.com/DiageoCareers"},
#     {"name": "ab-inbev", "provider": "workday", "base_url": "https://abinbev.wd3.myworkdayjobs.com/ABInBevCareers"},
#     {"name": "heineken", "provider": "workday", "base_url": "https://heineken.wd3.myworkdayjobs.com/HeinekenCareers"},
#     {"name": "itc", "provider": "workday", "base_url": "https://itc.wd3.myworkdayjobs.com/ITCCareers"},
#     {"name": "britannia", "provider": "workday", "base_url": "https://britannia.wd3.myworkdayjobs.com/BritanniaCareers"},
#     {"name": "godrej", "provider": "workday", "base_url": "https://godrej.wd3.myworkdayjobs.com/GodrejCareers"},

#     # --- TOP ENERGY, CHEMICALS & INDUSTRIAL MATH ---
#     {"name": "exxonmobil", "provider": "workday", "base_url": "https://exxonmobil.wd5.myworkdayjobs.com/ExxonMobilCareers"},
#     {"name": "chevron", "provider": "workday", "base_url": "https://chevron.wd5.myworkdayjobs.com/ChevronCareers"},
#     {"name": "shell", "provider": "workday", "base_url": "https://shell.wd3.myworkdayjobs.com/ShellCareers"},
#     {"name": "bp", "provider": "workday", "base_url": "https://bp.wd3.myworkdayjobs.com/BPCareers"},
#     {"name": "totalenergies", "provider": "workday", "base_url": "https://totalenergies.wd3.myworkdayjobs.com/TotalCareers"},
#     {"name": "equinor", "provider": "workday", "base_url": "https://equinor.wd3.myworkdayjobs.com/EquinorCareers"},
#     {"name": "eni", "provider": "workday", "base_url": "https://eni.wd3.myworkdayjobs.com/EniCareers"},
#     {"name": "slb", "provider": "workday", "base_url": "https://slb.wd1.myworkdayjobs.com/SLBCareers"},
#     {"name": "halliburton", "provider": "workday", "base_url": "https://halliburton.wd1.myworkdayjobs.com/HalliburtonCareers"},
#     {"name": "bakerhughes", "provider": "workday", "base_url": "https://bakerhughes.wd1.myworkdayjobs.com/BakerHughesCareers"},
#     {"name": "dow", "provider": "workday", "base_url": "https://dow.wd1.myworkdayjobs.com/DowCareers"},
#     {"name": "dupont", "provider": "workday", "base_url": "https://dupont.wd1.myworkdayjobs.com/DuPontCareers"},
#     {"name": "basf", "provider": "workday", "base_url": "https://basf.wd3.myworkdayjobs.com/BASFCareers"},
#     {"name": "linde", "provider": "workday", "base_url": "https://linde.wd3.myworkdayjobs.com/LindeCareers"},
#     {"name": "airliquide", "provider": "workday", "base_url": "https://airliquide.wd3.myworkdayjobs.com/AirLiquideCareers"},
#     {"name": "relianceindustries", "provider": "workday", "base_url": "https://reliance.wd3.myworkdayjobs.com/RILCareers"},
#     {"name": "adanigroup", "provider": "workday", "base_url": "https://adani.wd3.myworkdayjobs.com/AdaniCareers"},
#     {"name": "tatapower", "provider": "workday", "base_url": "https://tata.wd3.myworkdayjobs.com/TataPowerCareers"},
#     {"name": "ntpc", "provider": "workday", "base_url": "https://ntpc.wd3.myworkdayjobs.com/NTPCCareers"},
#     {"name": "ongc", "provider": "workday", "base_url": "https://ongc.wd3.myworkdayjobs.com/ONGCCareers"},

#     # --- TOP LOGISTICS, AVIATION & TRANSPORTATION ---
#     {"name": "fedex", "provider": "workday", "base_url": "https://fedex.wd1.myworkdayjobs.com/FedExCareers"},
#     {"name": "ups", "provider": "workday", "base_url": "https://ups.wd1.myworkdayjobs.com/UPSCareers"},
#     {"name": "dhl", "provider": "workday", "base_url": "https://dhl.wd3.myworkdayjobs.com/DHLCareers"},
#     {"name": "maersk", "provider": "workday", "base_url": "https://maersk.wd3.myworkdayjobs.com/MaerskCareers"},
#     {"name": "delta", "provider": "workday", "base_url": "https://delta.wd1.myworkdayjobs.com/DeltaCareers"},
#     {"name": "united", "provider": "workday", "base_url": "https://united.wd1.myworkdayjobs.com/UnitedCareers"},
#     {"name": "americanairlines", "provider": "workday", "base_url": "https://aa.wd1.myworkdayjobs.com/AACareers"},
#     {"name": "lufthansa", "provider": "workday", "base_url": "https://lufthansa.wd3.myworkdayjobs.com/LufthansaCareers"},
#     {"name": "singaporeair", "provider": "workday", "base_url": "https://sia.wd3.myworkdayjobs.com/SIACareers"},
#     {"name": "emirates", "provider": "workday", "base_url": "https://emirates.wd3.myworkdayjobs.com/EmiratesCareers"},
#     {"name": "indigo", "provider": "workday", "base_url": "https://indigo.wd3.myworkdayjobs.com/IndiGoCareers"},
#     {"name": "airindia", "provider": "workday", "base_url": "https://airindia.wd3.myworkdayjobs.com/AirIndiaCareers"},
#     {"name": "vistara", "provider": "workday", "base_url": "https://vistara.wd3.myworkdayjobs.com/VistaraCareers"},
#     {"name": "delhivery", "provider": "workday", "base_url": "https://delhivery.wd3.myworkdayjobs.com/DelhiveryCareers"},
#     {"name": "blue-dart", "provider": "workday", "base_url": "https://bluedart.wd3.myworkdayjobs.com/BlueDartCareers"},
#     {"name": "schneider-logistics", "provider": "workday", "base_url": "https://schneider.wd1.myworkdayjobs.com/SchneiderLogistics"},
#     {"name": "chrobinson", "provider": "workday", "base_url": "https://chrobinson.wd1.myworkdayjobs.com/CHRobinson"},
#     {"name": "expeditors", "provider": "workday", "base_url": "https://expeditors.wd1.myworkdayjobs.com/ExpeditorsCareers"},
#     {"name": "kuehne-nagel", "provider": "workday", "base_url": "https://kuehne.wd3.myworkdayjobs.com/KuehneNagelCareers"},
#     {"name": "dsv", "provider": "workday", "base_url": "https://dsv.wd3.myworkdayjobs.com/DSVCareers"},

#     # --- TOP FINTECH SPECIFIC & MORTGAGE EXTRACTIONS ---
#     {"name": "fico", "provider": "workday", "base_url": "https://fico.wd1.myworkdayjobs.com/External"},
#     {"name": "equifax", "provider": "workday", "base_url": "https://equifax.wd1.myworkdayjobs.com/EquifaxCareers"},
#     {"name": "transunion", "provider": "workday", "base_url": "https://transunion.wd1.myworkdayjobs.com/TransUnionCareers"},
#     {"name": "experian", "provider": "workday", "base_url": "https://experian.wd1.myworkdayjobs.com/ExperianCareers"},
#     {"name": "broadridge", "provider": "workday", "base_url": "https://broadridge.wd1.myworkdayjobs.com/BroadridgeCareers"},
#     {"name": "fis", "provider": "workday", "base_url": "https://fis.wd1.myworkdayjobs.com/FISCareers"},
#     {"name": "fiserv", "provider": "workday", "base_url": "https://fiserv.wd1.myworkdayjobs.com/FiservCareers"},
#     {"name": "jack-henry", "provider": "workday", "base_url": "https://jackhenry.wd1.myworkdayjobs.com/JackHenryCareers"},
#     {"name": "diebold-nixdorf", "provider": "workday", "base_url": "https://dieboldnixdorf.wd1.myworkdayjobs.com/DNCareers"},
#     {"name": "ncr", "provider": "workday", "base_url": "https://ncr.wd1.myworkdayjobs.com/NCRCareers"},
#     {"name": "western-union", "provider": "workday", "base_url": "https://westernunion.wd1.myworkdayjobs.com/WUCareers"},
#     {"name": "moneygram", "provider": "workday", "base_url": "https://moneygram.wd1.myworkdayjobs.com/MoneyGramCareers"},
#     {"name": "worldpay", "provider": "workday", "base_url": "https://worldpay.wd1.myworkdayjobs.com/WorldpayCareers"},
#     {"name": "adyen", "provider": "workday", "base_url": "https://adyen.wd3.myworkdayjobs.com/AdyenCareers"},
#     {"name": "klarna", "provider": "workday", "base_url": "https://klarna.wd3.myworkdayjobs.com/KlarnaCareers"},
#     {"name": "revolut", "provider": "workday", "base_url": "https://revolut.wd3.myworkdayjobs.com/RevolutCareers"},
#     {"name": "monzo", "provider": "workday", "base_url": "https://monzo.wd3.myworkdayjobs.com/MonzoCareers"},
#     {"name": "chime", "provider": "workday", "base_url": "https://chime.wd1.myworkdayjobs.com/ChimeCareers"},
#     {"name": "sofi", "provider": "workday", "base_url": "https://sofi.wd1.myworkdayjobs.com/SoFiCareers"},
#     {"name": "robinhood", "provider": "workday", "base_url": "https://robinhood.wd1.myworkdayjobs.com/RobinhoodCareers"},

#     # --- GEOSPATIAL, GRAPHICS & GAME STACKS ---
#     {"name": "ea", "provider": "workday", "base_url": "https://ea.wd1.myworkdayjobs.com/EACareers"},
#     {"name": "activision", "provider": "workday", "base_url": "https://activision.wd1.myworkdayjobs.com/ActivisionCareers"},
#     {"name": "ubisoft", "provider": "workday", "base_url": "https://ubisoft.wd3.myworkdayjobs.com/UbisoftCareers"},
#     {"name": "take2", "provider": "workday", "base_url": "https://take2.wd1.myworkdayjobs.com/Take2Careers"},
#     {"name": "epicgames", "provider": "workday", "base_url": "https://epicgames.wd1.myworkdayjobs.com/EpicCareers"},
#     {"name": "unity", "provider": "workday", "base_url": "https://unity.wd1.myworkdayjobs.com/UnityCareers"},
#     {"name": "roblox", "provider": "workday", "base_url": "https://roblox.wd1.myworkdayjobs.com/RobloxCareers"},
#     {"name": "sony-interactive", "provider": "workday", "base_url": "https://sie.wd1.myworkdayjobs.com/SIECareers"},
#     {"name": "nintendo", "provider": "workday", "base_url": "https://nintendo.wd1.myworkdayjobs.com/NintendoCareers"},
#     {"name": "sega", "provider": "workday", "base_url": "https://sega.wd3.myworkdayjobs.com/SegaCareers"},
#     {"name": "esrichina", "provider": "workday", "base_url": "https://esri.wd1.myworkdayjobs.com/EsriCareers"},
#     {"name": "trimble", "provider": "workday", "base_url": "https://trimble.wd1.myworkdayjobs.com/TrimbleCareers"},
#     {"name": "garmin", "provider": "workday", "base_url": "https://garmin.wd1.myworkdayjobs.com/GarminCareers"},
#     {"name": "here-tech", "provider": "workday", "base_url": "https://here.wd3.myworkdayjobs.com/HERECareers"},
#     {"name": "tomtom-wday", "provider": "workday", "base_url": "https://tomtom.wd3.myworkdayjobs.com/TomTomCareers"},
#     {"name": "mapmyindia", "provider": "workday", "base_url": "https://mapmyindia.wd3.myworkdayjobs.com/Careers"},
#     {"name": "maxar", "provider": "workday", "base_url": "https://maxar.wd1.myworkdayjobs.com/MaxarCareers"},
#     {"name": "planet-labs", "provider": "workday", "base_url": "https://planet.wd1.myworkdayjobs.com/PlanetCareers"},
#     {"name": "spire-global", "provider": "workday", "base_url": "https://spire.wd1.myworkdayjobs.com/SpireCareers"},
#     {"name": "blacksky", "provider": "workday", "base_url": "https://blacksky.wd1.myworkdayjobs.com/BlackSkyCareers"},

#     # --- TOP STREAMING, MEDIA & ADVERTISING ENTERPRISES ---
#     {"name": "netflix", "provider": "workday", "base_url": "https://netflix.wd1.myworkdayjobs.com/NetflixCareers"},
#     {"name": "disney", "provider": "workday", "base_url": "https://disney.wd5.myworkdayjobs.com/DisneyCareers"},
#     {"name": "paramount", "provider": "workday", "base_url": "https://paramount.wd1.myworkdayjobs.com/ParamountCareers"},
#     {"name": "warnerbros-discovery", "provider": "workday", "base_url": "https://wbd.wd5.myworkdayjobs.com/WBDCareers"},
#     {"name": "comcast", "provider": "workday", "base_url": "https://comcast.wd1.myworkdayjobs.com/ComcastCareers"},
#     {"name": "charter", "provider": "workday", "base_url": "https://charter.wd1.myworkdayjobs.com/CharterCareers"},
#     {"name": "cox", "provider": "workday", "base_url": "https://cox.wd1.myworkdayjobs.com/CoxCareers"},
#     {"name": "spotify", "provider": "workday", "base_url": "https://spotify.wd1.myworkdayjobs.com/SpotifyCareers"},
#     {"name": "pandora", "provider": "workday", "base_url": "https://siriusxm.wd1.myworkdayjobs.com/SiriusXMCareers"},
#     {"name": "iheartmedia", "provider": "workday", "base_url": "https://iheartmedia.wd1.myworkdayjobs.com/iHeartMediaCareers"},
#     {"name": "wpp", "provider": "workday", "base_url": "https://wpp.wd3.myworkdayjobs.com/WPPCareers"},
#     {"name": "publicis", "provider": "workday", "base_url": "https://publicis.wd3.myworkdayjobs.com/PublicisCareers"},
#     {"name": "omnicom", "provider": "workday", "base_url": "https://omnicom.wd1.myworkdayjobs.com/OmnicomCareers"},
#     {"name": "interpublic", "provider": "workday", "base_url": "https://interpublic.wd1.myworkdayjobs.com/IPGCareers"},
#     {"name": "dentsu", "provider": "workday", "base_url": "https://dentsu.wd3.myworkdayjobs.com/DentsuCareers"},
#     {"name": "mediacom", "provider": "workday", "base_url": "https://wpp.wd3.myworkdayjobs.com/MediaComCareers"},
#     {"name": "mindshare", "provider": "workday", "base_url": "https://wpp.wd3.myworkdayjobs.com/MindshareCareers"},
#     {"name": "wavemaker", "provider": "workday", "base_url": "https://wpp.wd3.myworkdayjobs.com/WavemakerCareers"},
#     {"name": "ogilvy", "provider": "workday", "base_url": "https://wpp.wd3.myworkdayjobs.com/OgilvyCareers"},
#     {"name": "leo-burnett", "provider": "workday", "base_url": "https://publicis.wd3.myworkdayjobs.com/LeoBurnett"},

#     # --- TOP HARDWARE ENGINEERING & DEVICE FABRICATION ---
#     {"name": "foxconn", "provider": "workday", "base_url": "https://foxconn.wd3.myworkdayjobs.com/FoxconnCareers"},
#     {"name": "pegatron", "provider": "workday", "base_url": "https://pegatron.wd3.myworkdayjobs.com/PegatronCareers"},
#     {"name": "wistron", "provider": "workday", "base_url": "https://wistron.wd3.myworkdayjobs.com/WistronCareers"},
#     {"name": "flex-electronics", "provider": "workday", "base_url": "https://flex.wd1.myworkdayjobs.com/FlexCareers"},
#     {"name": "jabil", "provider": "workday", "base_url": "https://jabil.wd1.myworkdayjobs.com/JabilCareers"},
#     {"name": "sanmina", "provider": "workday", "base_url": "https://sanmina.wd1.myworkdayjobs.com/SanminaCareers"},
#     {"name": "celestica", "provider": "workday", "base_url": "https://celestica.wd1.myworkdayjobs.com/CelesticaCareers"},
#     {"name": "plexus", "provider": "workday", "base_url": "https://plexus.wd1.myworkdayjobs.com/PlexusCareers"},
#     {"name": "ttm-tech", "provider": "workday", "base_url": "https://ttm.wd1.myworkdayjobs.com/TTMCareers"},
#     {"name": "benchmark-elec", "provider": "workday", "base_url": "https://benchmark.wd1.myworkdayjobs.com/BenchmarkCareers"},
#     {"name": "te-connectivity", "provider": "workday", "base_url": "https://te.wd1.myworkdayjobs.com/TECareers"},
#     {"name": "molex", "provider": "workday", "base_url": "https://molex.wd1.myworkdayjobs.com/MolexCareers"},
#     {"name": "amphenol", "provider": "workday", "base_url": "https://amphenol.wd1.myworkdayjobs.com/AmphenolCareers"},
#     {"name": "hirose", "provider": "workday", "base_url": "https://hirose.wd3.myworkdayjobs.com/HiroseCareers"},
#     {"name": "kyocera", "provider": "workday", "base_url": "https://kyocera.wd3.myworkdayjobs.com/KyoceraCareers"},
#     {"name": "murata", "provider": "workday", "base_url": "https://murata.wd3.myworkdayjobs.com/MurataCareers"},
#     {"name": "tdk", "provider": "workday", "base_url": "https://tdk.wd3.myworkdayjobs.com/TDKCareers"},
#     {"name": "taiyo-yuden", "provider": "workday", "base_url": "https://taiyo-yuden.wd3.myworkdayjobs.com/TaiyoCareers"},
#     {"name": "yageo", "provider": "workday", "base_url": "https://yageo.wd3.myworkdayjobs.com/YageoCareers"},
#     {"name": "panasonic", "provider": "workday", "base_url": "https://panasonic.wd3.myworkdayjobs.com/PanasonicCareers"},

#     # --- SCIENTIFIC DATA, INSTRUMENTS & RESEARCH LAYERS ---
#     {"name": "agilent", "provider": "workday", "base_url": "https://agilent.wd1.myworkdayjobs.com/AgilentCareers"},
#     {"name": "waters", "provider": "workday", "base_url": "https://waters.wd1.myworkdayjobs.com/WatersCareers"},
#     {"name": "perkinelmer", "provider": "workday", "base_url": "https://perkinelmer.wd1.myworkdayjobs.com/PKICareers"},
#     {"name": "bruker", "provider": "workday", "base_url": "https://bruker.wd1.myworkdayjobs.com/BrukerCareers"},
#     {"name": "m प्रवाह", "provider": "workday", "base_url": "https://mettler.wd3.myworkdayjobs.com/MettlerCareers"},
#     {"name": "shimadzu", "provider": "workday", "base_url": "https://shimadzu.wd3.myworkdayjobs.com/ShimadzuCareers"},
#     {"name": "illumina", "provider": "workday", "base_url": "https://illumina.wd1.myworkdayjobs.com/IlluminaCareers"},
#     {"name": "qiagen", "provider": "workday", "base_url": "https://qiagen.wd3.myworkdayjobs.com/QiagenCareers"},
#     {"name": "eurofins", "provider": "workday", "base_url": "https://eurofins.wd3.myworkdayjobs.com/EurofinsCareers"},
#     {"name": "sgs-group", "provider": "workday", "base_url": "https://sgs.wd3.myworkdayjobs.com/SGSCareers"},
#     {"name": "intertek", "provider": "workday", "base_url": "https://intertek.wd3.myworkdayjobs.com/IntertekCareers"},
#     {"name": "bureau-veritas", "provider": "workday", "base_url": "https://bv.wd3.myworkdayjobs.com/BVCareers"},
#     {"name": "tuv-sud", "provider": "workday", "base_url": "https://tuv.wd3.myworkdayjobs.com/TUVSUDCareers"},
#     {"name": "tuv-rheinland", "provider": "workday", "base_url": "https://tuv.wd3.myworkdayjobs.com/TRHCareers"},
#     {"name": "applusrhein", "provider": "workday", "base_url": "https://applus.wd3.myworkdayjobs.com/ApplusCareers"},
#     {"name": "dnv-gl", "provider": "workday", "base_url": "https://dnv.wd3.myworkdayjobs.com/DNVCareers"},
#     {"name": "lloyds-register", "provider": "workday", "base_url": "https://lr.wd3.myworkdayjobs.com/LRCareers"},
#     {"name": "abs-group", "provider": "workday", "base_url": "https://abs.wd1.myworkdayjobs.com/ABSCareers"},
#     {"name": "ricardo-eng", "provider": "workday", "base_url": "https://ricardo.wd3.myworkdayjobs.com/RicardoCareers"},
#     {"name": "avl-list", "provider": "workday", "base_url": "https://avl.wd3.myworkdayjobs.com/AVLCareers"}
# ]

WORKDAY_COMPANIES = [

    {
        "name": "paypal",
        "provider": "workday",
        "base_url":
        "https://paypal.wd1.myworkdayjobs.com"
    },

    {
        "name": "ge",
        "provider": "workday",
        "base_url":
        "https://ge.wd5.myworkdayjobs.com"
    }
]